plugins:
  # - jekyll-relative-links # included by github
  # - jekyll-paginate # included by github
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

remote_theme             : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "A Story of LX"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "LX"
description              : ""
url                      : # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : luxuwin/blog.github.io # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
# # breadcrumbs            : false # true, false (default)
words_per_minute         : 200

# Conversion
markdown: kramdown
# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter_opts:
    disable : true

# comments:
# Comments are added via [Utterances](https://medium.com/@argszero.reg/building-a-math-blog-with-github-pages-jekyll-mathjax-and-utterances-a-diy-guide-f07727d33716)

reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : true # true, false (default)
search_full_content      : true # true, false (default)
search_provider          : lunr # lunr (default), algolia, google

# Analytics
analytics:
  provider               : "google" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :  UA-166298388-1
    anonymize_ip         : # true, false (default)

paginate: 8
paginate_path: /page:num/
timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  - scope:
      path: ""
      type: posts_with_comments
    values:
      layout: single
      entries_layout: grid
      comments: true
      related: true

# export certain folders (e.g. 'pages' means files under _pages will be exported.)
collections:
  pages:
    output: true
    permalink: /:collection/:path/
    

# Site Author
author:
  name             : "LX"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : # "I am an **amazing** person."
  location         : "US"
  email            :
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:luxu@luxu.win"
    # - label: "Website"
    #   icon: "fas fa-fw fa-link"
    #   # url: "https://your-website.com"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   # url: "https://twitter.com/"
    # - label: "Facebook"
    #   icon: "fab fa-fw fa-facebook-square"
    #   # url: "https://facebook.com/"
    # - label: "GitHub"
    #   icon: "fab fa-fw fa-github"
    #   # url: "https://github.com/"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"
